package com.example.metadata

import android.content.Context
import android.util.Log
import com.example.data.AppDatabase
import com.example.data.TrackDao
import com.example.model.MetadataWriteState
import com.example.model.Track
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Semaphore
import kotlinx.coroutines.sync.withPermit
import kotlinx.coroutines.withContext
import java.io.File
import java.util.concurrent.atomic.AtomicInteger

/**
 * Report generated by library embedded metadata repair/migration.
 */
data class LibraryMigrationReport(
    val totalExamined: Int = 0,
    val successfullyWritten: Int = 0,
    val alreadySynchronized: Int = 0,
    val failed: Int = 0,
    val skippedReadOnlyOrUnsupported: Int = 0
)

/**
 * Background writer queue with controlled concurrency (1-2 concurrent jobs).
 *
 * Ensures audio file tag writing never blocks the main UI or causes audio stuttering,
 * performs read-back verification for every write, updates persistent track status in Room DB,
 * and provides library migration/repair utilities.
 */
class MetadataFileWriteQueue private constructor(
    private val context: Context,
    private val injectedTrackDao: TrackDao? = null,
    private val injectedFileWriter: MetadataFileWriter? = null
) {

    companion object {
        private const val TAG = "MetadataFileWriteQueue"
        private const val MAX_CONCURRENT_WRITES = 2

        @Volatile
        private var INSTANCE: MetadataFileWriteQueue? = null

        fun getInstance(context: Context): MetadataFileWriteQueue {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: MetadataFileWriteQueue(context.applicationContext).also { INSTANCE = it }
            }
        }

        fun createForTesting(
            context: Context,
            trackDao: TrackDao,
            fileWriter: MetadataFileWriter? = null
        ): MetadataFileWriteQueue {
            return MetadataFileWriteQueue(context, trackDao, fileWriter)
        }
    }

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val semaphore = Semaphore(MAX_CONCURRENT_WRITES)
    private val trackDao: TrackDao? = injectedTrackDao ?: try {
        AppDatabase.getDatabase(context).trackDao()
    } catch (_: Throwable) {
        null
    }
    private val fileWriter = injectedFileWriter ?: MetadataFileWriter(context, trackDao)

    private val activeCount = AtomicInteger(0)
    private val _isWriting = MutableStateFlow(false)
    val isWriting: StateFlow<Boolean> = _isWriting.asStateFlow()

    private val _activeWritesCount = MutableStateFlow(0)
    val activeWritesCount: StateFlow<Int> = _activeWritesCount.asStateFlow()

    private val _lastMigrationReport = MutableStateFlow<LibraryMigrationReport?>(null)
    val lastMigrationReport: StateFlow<LibraryMigrationReport?> = _lastMigrationReport.asStateFlow()

    /**
     * Queues an asynchronous file metadata write with controlled concurrency.
     * Updates track status in DB to WRITING_TO_FILE immediately.
     */
    fun enqueue(
        track: Track,
        artworkBytes: ByteArray? = null,
        artworkMimeType: String = "image/jpeg",
        onComplete: ((MetadataWriteResult) -> Unit)? = null
    ): Job {
        return scope.launch {
            if (track.id.isNotBlank()) {
                try {
                    trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.WRITING_TO_FILE.name)
                } catch (_: Exception) {}
            }

            activeCount.incrementAndGet()
            _activeWritesCount.value = activeCount.get()
            _isWriting.value = true

            val result = semaphore.withPermit {
                fileWriter.writeAsync(track, artworkBytes, artworkMimeType)
            }

            val current = activeCount.decrementAndGet()
            _activeWritesCount.value = current
            if (current <= 0) {
                _isWriting.value = false
            }

            onComplete?.invoke(result)
        }
    }

    /**
     * Synchronous / suspend write for situations requiring immediate completion.
     */
    suspend fun writeDirect(
        track: Track,
        artworkBytes: ByteArray? = null,
        artworkMimeType: String = "image/jpeg"
    ): MetadataWriteResult = semaphore.withPermit {
        fileWriter.writeAsync(track, artworkBytes, artworkMimeType)
    }

    /**
     * Scans the database library for tracks whose metadata has not been physically written to disk
     * (or is out of sync), and embeds the latest database metadata into each file.
     *
     * Smart sync: If the file already physically contains all metadata from the database,
     * the track state is marked FILE_WRITE_SUCCESS without an unnecessary file rewrite.
     */
    suspend fun repairOrMigrateLibrary(
        onProgress: ((current: Int, total: Int, trackTitle: String) -> Unit)? = null
    ): LibraryMigrationReport = withContext(Dispatchers.IO) {
        val tracksNeedingWrite = trackDao?.getTracksNeedingFileWrite()?.map { it.toTrack() } ?: emptyList()
        val total = tracksNeedingWrite.size
        var writtenCount = 0
        var syncedCount = 0
        var failedCount = 0
        var skippedCount = 0

        Log.i(TAG, "Starting library embedded metadata migration for $total tracks...")

        for ((index, track) in tracksNeedingWrite.withIndex()) {
            onProgress?.invoke(index + 1, total, track.title)

            val path = track.filePath
            if (path.isBlank() || path.startsWith("demo://") || path.startsWith("http")) {
                skippedCount++
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FORMAT_WRITE_UNSUPPORTED.name)
                continue
            }

            val isContentUri = path.startsWith("content://")
            val file = if (!isContentUri) File(path) else null

            if (file != null && (!file.exists() || !file.canWrite())) {
                val state = if (!file.exists()) MetadataWriteState.FILE_WRITE_FAILED else MetadataWriteState.READ_ONLY_FILE
                trackDao?.updateMetadataWriteState(track.id, state.name)
                skippedCount++
                continue
            }

            // Read physical tags from file
            val physical = AudioEmbeddedMetadataReader.read(context, path)

            // Check if physical file is already in sync with database
            val titleMatches = track.title.isBlank() || physical.title.equals(track.title, ignoreCase = true)
            val artistMatches = track.artist.isBlank() || physical.artist.equals(track.artist, ignoreCase = true)
            val albumMatches = track.album.isBlank() || track.album == "Single" || track.album == "Unknown Album" ||
                    physical.album.equals(track.album, ignoreCase = true)
            val bpmMatches = track.bpm <= 0.0 || (physical.bpm != null && kotlin.math.abs(physical.bpm - track.bpm) < 1.0)
            val keyMatches = track.musicalKey.isBlank() || track.musicalKey == "—" || track.musicalKey == "-" ||
                    physical.musicalKey.equals(track.musicalKey, ignoreCase = true)

            val alreadyInSync = titleMatches && artistMatches && albumMatches && bpmMatches && keyMatches

            if (alreadyInSync && (physical.title != null || physical.artist != null)) {
                // File already has the tags! Mark as embedded
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                syncedCount++
            } else {
                // Need to embed metadata into file
                val writeRes = semaphore.withPermit {
                    fileWriter.writeAsync(track)
                }
                when (writeRes) {
                    is MetadataWriteResult.Written -> writtenCount++
                    is MetadataWriteResult.Partial -> writtenCount++
                    is MetadataWriteResult.ReadOnlyFile, is MetadataWriteResult.Unsupported, is MetadataWriteResult.PermissionRequired -> skippedCount++
                    is MetadataWriteResult.Failed, is MetadataWriteResult.VerificationFailed -> failedCount++
                }
            }
        }

        val report = LibraryMigrationReport(
            totalExamined = total,
            successfullyWritten = writtenCount,
            alreadySynchronized = syncedCount,
            failed = failedCount,
            skippedReadOnlyOrUnsupported = skippedCount
        )
        _lastMigrationReport.value = report
        Log.i(TAG, "Completed library embedded metadata migration: $report")
        report
    }
}
