package com.example.metadata

import android.content.Context
import android.util.Log
import com.example.data.AppDatabase
import com.example.data.TrackDao
import com.example.model.MetadataWriteState
import com.example.model.Track
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Semaphore
import kotlinx.coroutines.sync.withPermit
import kotlinx.coroutines.withContext
import java.io.File
import java.util.concurrent.atomic.AtomicInteger

/**
 * Real-time operational phase during bulk metadata push.
 */
enum class PushMetadataPhase(val label: String) {
    READING_PHYSICAL("Reading physical tags"),
    COMPARING("Comparing metadata"),
    WRITING_TAGS("Writing tags to file"),
    VERIFYING("Verifying written metadata"),
    DONE_SYNCED("Done / Skipped (already in sync)"),
    DONE_WRITTEN("Done (written to file)"),
    FAILED("Failed")
}

/**
 * Real-time progress feedback during bulk metadata push.
 */
data class PushMetadataProgress(
    val current: Int = 0,
    val total: Int = 0,
    val trackTitle: String = "",
    val trackArtist: String = "",
    val fileName: String = "",
    val phase: PushMetadataPhase = PushMetadataPhase.READING_PHYSICAL,
    val writtenCount: Int = 0,
    val syncedCount: Int = 0,
    val failedCount: Int = 0
)

/**
 * Detail of a failure during bulk metadata push.
 */
data class PushMetadataFailure(
    val trackId: String,
    val title: String,
    val artist: String,
    val filePath: String,
    val reason: String
)

/**
 * Comprehensive summary report generated after Push Metadata to Files completes.
 */
data class PushMetadataReport(
    val totalExamined: Int = 0,
    val successfullyWritten: Int = 0,
    val alreadySynchronized: Int = 0,
    val failed: Int = 0,
    val failureReasons: List<PushMetadataFailure> = emptyList()
)

/**
 * Report generated by library embedded metadata repair/migration.
 */
data class LibraryMigrationReport(
    val totalExamined: Int = 0,
    val successfullyWritten: Int = 0,
    val alreadySynchronized: Int = 0,
    val failed: Int = 0,
    val skippedReadOnlyOrUnsupported: Int = 0
)

/**
 * Background writer queue with controlled concurrency (1-2 concurrent jobs).
 *
 * Ensures audio file tag writing never blocks the main UI or causes audio stuttering,
 * performs read-back verification for every write, updates persistent track status in Room DB,
 * and provides library migration/repair utilities.
 */
class MetadataFileWriteQueue private constructor(
    private val context: Context,
    private val injectedTrackDao: TrackDao? = null,
    private val injectedFileWriter: MetadataFileWriter? = null
) {

    companion object {
        private const val TAG = "MetadataFileWriteQueue"
        private const val MAX_CONCURRENT_WRITES = 2

        @Volatile
        private var INSTANCE: MetadataFileWriteQueue? = null

        fun getInstance(context: Context): MetadataFileWriteQueue {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: MetadataFileWriteQueue(context.applicationContext).also { INSTANCE = it }
            }
        }

        fun createForTesting(
            context: Context,
            trackDao: TrackDao,
            fileWriter: MetadataFileWriter? = null
        ): MetadataFileWriteQueue {
            return MetadataFileWriteQueue(context, trackDao, fileWriter)
        }
    }

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val semaphore = Semaphore(MAX_CONCURRENT_WRITES)
    private val trackDao: TrackDao? = injectedTrackDao ?: try {
        AppDatabase.getDatabase(context).trackDao()
    } catch (_: Throwable) {
        null
    }
    private val fileWriter = injectedFileWriter ?: MetadataFileWriter(context, trackDao)

    private val activeCount = AtomicInteger(0)
    private val _isWriting = MutableStateFlow(false)
    val isWriting: StateFlow<Boolean> = _isWriting.asStateFlow()

    private val _activeWritesCount = MutableStateFlow(0)
    val activeWritesCount: StateFlow<Int> = _activeWritesCount.asStateFlow()

    private val _lastMigrationReport = MutableStateFlow<LibraryMigrationReport?>(null)
    val lastMigrationReport: StateFlow<LibraryMigrationReport?> = _lastMigrationReport.asStateFlow()

    private val _isPushingMetadata = MutableStateFlow(false)
    val isPushingMetadata: StateFlow<Boolean> = _isPushingMetadata.asStateFlow()

    private val _pushProgress = MutableStateFlow<PushMetadataProgress?>(null)
    val pushProgress: StateFlow<PushMetadataProgress?> = _pushProgress.asStateFlow()

    private val _lastPushReport = MutableStateFlow<PushMetadataReport?>(null)
    val lastPushReport: StateFlow<PushMetadataReport?> = _lastPushReport.asStateFlow()

    private var pushJob: Job? = null

    fun cancelPushMetadata() {
        pushJob?.cancel()
        _isPushingMetadata.value = false
    }

    /**
     * Queues an asynchronous file metadata write with controlled concurrency.
     * Updates track status in DB to WRITING_TO_FILE immediately.
     */
    fun enqueue(
        track: Track,
        artworkBytes: ByteArray? = null,
        artworkMimeType: String = "image/jpeg",
        onComplete: ((MetadataWriteResult) -> Unit)? = null
    ): Job {
        return scope.launch {
            if (track.id.isNotBlank()) {
                try {
                    trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.WRITING_TO_FILE.name)
                } catch (_: Exception) {}
            }

            activeCount.incrementAndGet()
            _activeWritesCount.value = activeCount.get()
            _isWriting.value = true

            val result = semaphore.withPermit {
                fileWriter.writeAsync(track, artworkBytes, artworkMimeType)
            }

            val current = activeCount.decrementAndGet()
            _activeWritesCount.value = current
            if (current <= 0) {
                _isWriting.value = false
            }

            onComplete?.invoke(result)
        }
    }

    /**
     * Synchronous / suspend write for situations requiring immediate completion.
     */
    suspend fun writeDirect(
        track: Track,
        artworkBytes: ByteArray? = null,
        artworkMimeType: String = "image/jpeg"
    ): MetadataWriteResult = semaphore.withPermit {
        fileWriter.writeAsync(track, artworkBytes, artworkMimeType)
    }

    /**
     * Scans the database library for tracks whose metadata has not been physically written to disk
     * (or is out of sync), and embeds the latest database metadata into each file.
     *
     * Smart sync: If the file already physically contains all metadata from the database,
     * the track state is marked FILE_WRITE_SUCCESS without an unnecessary file rewrite.
     */
    suspend fun repairOrMigrateLibrary(
        onProgress: ((current: Int, total: Int, trackTitle: String) -> Unit)? = null
    ): LibraryMigrationReport = withContext(Dispatchers.IO) {
        val tracksNeedingWrite = trackDao?.getTracksNeedingFileWrite()?.map { it.toTrack() } ?: emptyList()
        val total = tracksNeedingWrite.size
        var writtenCount = 0
        var syncedCount = 0
        var failedCount = 0
        var skippedCount = 0

        Log.i(TAG, "Starting library embedded metadata migration for $total tracks...")

        for ((index, track) in tracksNeedingWrite.withIndex()) {
            onProgress?.invoke(index + 1, total, track.title)

            val path = track.filePath
            if (path.isBlank() || path.startsWith("demo://") || path.startsWith("http")) {
                skippedCount++
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FORMAT_WRITE_UNSUPPORTED.name)
                continue
            }

            val isContentUri = path.startsWith("content://")
            val file = if (!isContentUri) File(path) else null

            if (file != null && (!file.exists() || !file.canWrite())) {
                val state = if (!file.exists()) MetadataWriteState.FILE_WRITE_FAILED else MetadataWriteState.READ_ONLY_FILE
                trackDao?.updateMetadataWriteState(track.id, state.name)
                skippedCount++
                continue
            }

            // Read physical tags from file
            val physical = AudioEmbeddedMetadataReader.read(context, path)

            // Check if physical file is already in sync with database
            val titleMatches = track.title.isBlank() || physical.title.equals(track.title, ignoreCase = true)
            val artistMatches = track.artist.isBlank() || physical.artist.equals(track.artist, ignoreCase = true)
            val albumMatches = track.album.isBlank() || track.album == "Single" || track.album == "Unknown Album" ||
                    physical.album.equals(track.album, ignoreCase = true)
            val bpmMatches = track.bpm <= 0.0 || (physical.bpm != null && kotlin.math.abs(physical.bpm - track.bpm) < 1.0)
            val keyMatches = track.musicalKey.isBlank() || track.musicalKey == "—" || track.musicalKey == "-" ||
                    physical.musicalKey.equals(track.musicalKey, ignoreCase = true)

            val alreadyInSync = titleMatches && artistMatches && albumMatches && bpmMatches && keyMatches

            if (alreadyInSync && (physical.title != null || physical.artist != null)) {
                // File already has the tags! Mark as embedded
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                syncedCount++
            } else {
                // Need to embed metadata into file
                val writeRes = semaphore.withPermit {
                    fileWriter.writeAsync(track)
                }
                when (writeRes) {
                    is MetadataWriteResult.Written -> writtenCount++
                    is MetadataWriteResult.Partial -> writtenCount++
                    is MetadataWriteResult.ReadOnlyFile, is MetadataWriteResult.Unsupported, is MetadataWriteResult.PermissionRequired -> skippedCount++
                    is MetadataWriteResult.Failed, is MetadataWriteResult.VerificationFailed -> failedCount++
                }
            }
        }

        val report = LibraryMigrationReport(
            totalExamined = total,
            successfullyWritten = writtenCount,
            alreadySynchronized = syncedCount,
            failed = failedCount,
            skippedReadOnlyOrUnsupported = skippedCount
        )
        _lastMigrationReport.value = report
        Log.i(TAG, "Completed library embedded metadata migration: $report")
        report
    }

    /**
     * Executes the authoritative 12-step bulk "Push Metadata to Files" operation
     * across the entire library:
     * 1. Reads all tracks in the SoundSync library.
     * 2. Reads SoundSync's existing metadata database.
     * 3. Reads actual embedded metadata from every physical file.
     * 4. Compares the two.
     * 5. Determines which fields need writing.
     * 6. Writes SoundSync metadata into the physical audio file (dual INFO + id3 on WAV, ID3v2.3, Vorbis, etc.).
     * 7. Closes the writer.
     * 8. Reopens the physical file.
     * 9. Reads the tags back.
     * 10. Verifies that they were actually written.
     * 11. Updates the track status in Room DB.
     * 12. Continues to the next track.
     */
    suspend fun pushMetadataToFiles(
        forceAll: Boolean = true,
        onProgress: ((PushMetadataProgress) -> Unit)? = null
    ): PushMetadataReport = withContext(Dispatchers.IO) {
        _isPushingMetadata.value = true
        val allTracks = trackDao?.getAllTracksList()?.map { it.toTrack() } ?: emptyList()
        val total = allTracks.size

        var writtenCount = 0
        var syncedCount = 0
        var failedCount = 0
        val failures = mutableListOf<PushMetadataFailure>()

        try {
            for ((index, track) in allTracks.withIndex()) {
                coroutineContext.ensureActive()
                val current = index + 1
                val fileName = File(track.filePath).name.ifBlank { track.filePath }

                val updateProgress = { phase: PushMetadataPhase ->
                    val p = PushMetadataProgress(
                        current = current,
                        total = total,
                        trackTitle = track.title.ifBlank { fileName },
                        trackArtist = track.artist.ifBlank { "Unknown Artist" },
                        fileName = fileName,
                        phase = phase,
                        writtenCount = writtenCount,
                        syncedCount = syncedCount,
                        failedCount = failedCount
                    )
                    _pushProgress.value = p
                    onProgress?.invoke(p)
                }

                // Step 3: Read actual embedded metadata from physical file
                updateProgress(PushMetadataPhase.READING_PHYSICAL)
                val path = track.filePath
                if (path.isBlank() || path.startsWith("demo://") || path.startsWith("http")) {
                    syncedCount++
                    updateProgress(PushMetadataPhase.DONE_SYNCED)
                    continue
                }

                val physical = AudioEmbeddedMetadataReader.read(context, path)

                // Step 4 & 5: Compare the two & determine which fields need writing
                updateProgress(PushMetadataPhase.COMPARING)

                val titleNeedsWrite = track.title.isNotBlank() &&
                        track.title != "Unknown Title" &&
                        !track.title.equals(physical.title, ignoreCase = true)

                val artistNeedsWrite = track.artist.isNotBlank() &&
                        track.artist != "Unknown Artist" &&
                        !track.artist.equals(physical.artist, ignoreCase = true)

                val albumNeedsWrite = track.album.isNotBlank() &&
                        track.album != "Single" &&
                        track.album != "Unknown Album" &&
                        !track.album.equals(physical.album, ignoreCase = true)

                val genreNeedsWrite = track.genre.isNotBlank() &&
                        track.genre != "DJ Library" &&
                        track.genre != "Club" &&
                        track.genre != "Unknown Genre" &&
                        !track.genre.equals(physical.genre, ignoreCase = true)

                val yearNeedsWrite = track.releaseYear != null &&
                        track.releaseYear > 0 &&
                        track.releaseYear != physical.releaseYear

                val bpmNeedsWrite = track.bpm > 0.0 &&
                        (physical.bpm == null || kotlin.math.abs(physical.bpm - track.bpm) > 1.0)

                val keyNeedsWrite = track.musicalKey.isNotBlank() &&
                        track.musicalKey != "—" &&
                        track.musicalKey != "-" &&
                        !track.musicalKey.equals(physical.musicalKey, ignoreCase = true)

                val trackNumberNeedsWrite = track.trackNumber > 0 &&
                        track.trackNumber != physical.trackNumber

                val hasDbArtwork = !track.artworkCachePath.isNullOrBlank() || !track.artworkUrl.isNullOrBlank()
                val artworkNeedsWrite = hasDbArtwork && (!physical.hasEmbeddedArtwork || physical.embeddedArtworkSize <= 0)

                val hasAnyDifference = titleNeedsWrite || artistNeedsWrite || albumNeedsWrite ||
                        genreNeedsWrite || yearNeedsWrite || bpmNeedsWrite || keyNeedsWrite ||
                        trackNumberNeedsWrite || artworkNeedsWrite

                val hasPhysicalTags = physical.title != null || physical.artist != null || physical.bpm != null

                if (!hasAnyDifference && hasPhysicalTags && !forceAll) {
                    syncedCount++
                    trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                    updateProgress(PushMetadataPhase.DONE_SYNCED)
                    continue
                }

                if (!hasAnyDifference && hasPhysicalTags) {
                    syncedCount++
                    trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                    updateProgress(PushMetadataPhase.DONE_SYNCED)
                    continue
                }

                // Step 6: Write SoundSync metadata into physical audio file
                updateProgress(PushMetadataPhase.WRITING_TAGS)

                val activeArtworkBytes = track.artworkCachePath?.let { cachePath ->
                    try {
                        val f = File(cachePath)
                        if (f.exists() && f.canRead()) f.readBytes() else null
                    } catch (_: Exception) { null }
                }

                val writeResult = semaphore.withPermit {
                    fileWriter.writeAsync(track, activeArtworkBytes)
                }

                // Step 7: Writer is closed internally
                // Step 8, 9, 10: Reopen physical file, read tags back, verify
                updateProgress(PushMetadataPhase.VERIFYING)

                // Step 11: Update track status
                when (writeResult) {
                    is MetadataWriteResult.Written, is MetadataWriteResult.Partial -> {
                        writtenCount++
                        updateProgress(PushMetadataPhase.DONE_WRITTEN)
                    }
                    is MetadataWriteResult.ReadOnlyFile -> {
                        failedCount++
                        failures.add(PushMetadataFailure(track.id, track.title, track.artist, path, "File is read-only on device storage"))
                        updateProgress(PushMetadataPhase.FAILED)
                    }
                    is MetadataWriteResult.PermissionRequired -> {
                        failedCount++
                        failures.add(PushMetadataFailure(track.id, track.title, track.artist, path, "Permission required to access file or content URI"))
                        updateProgress(PushMetadataPhase.FAILED)
                    }
                    is MetadataWriteResult.Unsupported -> {
                        failedCount++
                        failures.add(PushMetadataFailure(track.id, track.title, track.artist, path, "Format not supported for tag writing"))
                        updateProgress(PushMetadataPhase.FAILED)
                    }
                    is MetadataWriteResult.VerificationFailed -> {
                        failedCount++
                        failures.add(PushMetadataFailure(track.id, track.title, track.artist, path, "Verification failed for ${writeResult.field}: expected '${writeResult.expected}', got '${writeResult.actual}'"))
                        updateProgress(PushMetadataPhase.FAILED)
                    }
                    is MetadataWriteResult.Failed -> {
                        failedCount++
                        failures.add(PushMetadataFailure(track.id, track.title, track.artist, path, writeResult.reason))
                        updateProgress(PushMetadataPhase.FAILED)
                    }
                }
                // Step 12: Continue to next track
            }
        } catch (e: CancellationException) {
            Log.i(TAG, "Push metadata to files was cancelled by user.")
        } finally {
            _isPushingMetadata.value = false
        }

        val report = PushMetadataReport(
            totalExamined = total,
            successfullyWritten = writtenCount,
            alreadySynchronized = syncedCount,
            failed = failedCount,
            failureReasons = failures
        )
        _lastPushReport.value = report
        Log.i(TAG, "Push metadata to files completed: $report")
        report
    }
}
